name: Continuous Integration

on:
    push:
        branches:
            - release
    workflow_dispatch:

concurrency:
    group: branch-release

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Generate Token
              id: generate_token
              uses: tibdex/github-app-token@v1
              with:
                  app_id: ${{ vars.TOKEN_APP_ID }}
                  private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 5
                  token: ${{ steps.generate_token.outputs.token }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Setup
              run: yarn install
            - name: Build
              run: yarn build
            - name: Publish
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
                  mv npmrc-ci .npmrc
                  npx turbo run release --concurrency 1 -- --prerelease testing --skip.tag --skip.changelog
                  npx turbo run deploy -- --tag testing
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Push Changes
              run: |
                  git fetch origin
                  git merge -m "Merge branch 'release' [skip ci]" origin/release
                  git push origin HEAD:release
